// Pure park module: how a run puts an issue down without losing it (PRD §5
// item 6, "Ping and Park"). The four-step order below is exact and
// load-bearing — it lets a crashed run tell "mid-Park" from "finished Park"
// apart and resume without repeating a step or re-asking the maintainer's
// question. No fs, no process, no clock reads — callers pass in what they
// observed.

import type { GateKind } from "./agentwork";

// ───── the park reasons

export type ParkReason =
  | { k: "unanswered-question"; question: string; askedAt: string }
  | { k: "gate-failed"; gates: GateKind[]; toClear: string }
  | { k: "implement-failed"; reason: string }
  | { k: "merge-declined" };

const AI_DISCLAIMER = "> *This was generated by AI during triage.*";

function reasonText(reason: ParkReason): string {
  switch (reason.k) {
    case "unanswered-question":
      return `Unanswered question (asked at ${reason.askedAt}): ${reason.question}`;
    case "gate-failed":
      return `Landing gate(s) failed: ${reason.gates.join(", ")}. To clear: ${reason.toClear}`;
    case "implement-failed":
      return `Implementation failed: ${reason.reason}`;
    case "merge-declined":
      return "The merge was declined by the maintainer.";
  }
}

/**
 * The durable tracker-comment text for step 2 of Park: the AI disclaimer
 * first (so a reader sees at a glance this wasn't the maintainer), then the
 * reason, the branch the work survives on, and what state that work is in.
 * Pure text — posting it is the caller's job.
 */
export function parkCommentText(reason: ParkReason, branch: string, workState: string): string {
  return [AI_DISCLAIMER, "", reasonText(reason), "", `Branch: ${branch}`, `Shelved work: ${workState}`].join("\n");
}

// ───── the park plan

export type ParkStep = "push-branch" | "post-comment" | "release-claim" | "swap-label" | "set-unstarted";

/** The journal's `step` value while a Park is in flight — one definition, so
 * the writer and recovery cannot drift apart on the spelling. */
export const PARK_STEP = "park";

/**
 * The Park steps in their exact, load-bearing order (PRD §5 item 6): push the
 * branch, comment the reason, release the tracker claim, then drop
 * ready-for-agent for needs-info and move the ticket back to unstarted.
 *
 * That last one is two tracker writes, not one, and they are listed
 * separately because PROTOCOL's Park step 3 says both matter: Queue selection
 * needs `ready-for-agent` AND an unstarted state, so a run that crashed
 * between them leaves a ticket that no re-labelling alone can rescue.
 * Splitting them is what lets remainingPark resume at the write that is
 * actually still owed.
 *
 * The order never varies by reason, so this takes no argument.
 */
export function parkPlan(): ParkStep[] {
  return ["push-branch", "post-comment", "release-claim", "swap-label", "set-unstarted"];
}

// ───── recovery: what a crashed run still owes

// Real crash states are always a prefix of the step order — a later step
// cannot have run before an earlier one. Input that is not a prefix describes
// a state no run can reach, and is not defended against.
export type ParkObserved = {
  branchPushed: boolean;
  commentPosted: boolean;
  claimReleased: boolean;
  labelSwapped: boolean;
  stateUnstarted: boolean;
};

/**
 * The steps a crashed run has not yet completed, in order. A run that
 * observes branchPushed=true owes no push and resumes at the comment — it
 * must never re-derive or re-ask the question, only replay the durable
 * comment already computed from the original reason (S19). Re-asking is
 * impossible by construction: ParkStep has no ask variant, so nothing this
 * returns can send the maintainer a second question.
 */
export function remainingPark(observed: ParkObserved): ParkStep[] {
  const steps: [ParkStep, boolean][] = [
    ["push-branch", observed.branchPushed],
    ["post-comment", observed.commentPosted],
    ["release-claim", observed.claimReleased],
    ["swap-label", observed.labelSwapped],
    ["set-unstarted", observed.stateUnstarted],
  ];
  return steps.filter(([, done]) => !done).map(([step]) => step);
}
