import { test, expect } from "bun:test";
import { parkCommentText, parkPlan, remainingPark } from "../src/park";
import type { ParkObserved, ParkReason } from "../src/park";

// ───── fixtures

const branch = "42/park-recovery";

const unanswered: ParkReason = {
  k: "unanswered-question",
  question: "squash or merge for this one?",
  askedAt: "2026-08-01T10:00:00Z",
};

const gateFailed: ParkReason = {
  k: "gate-failed",
  gates: ["tests", "review.spec"],
  toClear: "fix the two failing unit tests and address the spec review comments",
};

const implementFailed: ParkReason = {
  k: "implement-failed",
  reason: "could not locate the file referenced in the brief",
};

const mergeDeclined: ParkReason = { k: "merge-declined" };

const ALL_REASONS: ParkReason[] = [unanswered, gateFailed, implementFailed, mergeDeclined];

const NOTHING_DONE: ParkObserved = {
  branchPushed: false,
  commentPosted: false,
  claimReleased: false,
  labelSwapped: false,
  stateUnstarted: false,
};

const EVERYTHING_DONE: ParkObserved = {
  branchPushed: true,
  commentPosted: true,
  claimReleased: true,
  labelSwapped: true,
  stateUnstarted: true,
};

// ───── parkCommentText: durable text per reason

test("unanswered-question comment carries the AI disclaimer, the question, and the branch name", () => {
  const text = parkCommentText(unanswered, branch, "3 commits pushed, tests unrun");

  expect(text.startsWith("> *This was generated by AI during triage.*")).toBe(true);
  expect(text).toContain("squash or merge for this one?");
  expect(text).toContain(branch);
});

test("gate-failed comment carries the AI disclaimer, the failing gate(s), and the branch name", () => {
  const text = parkCommentText(gateFailed, branch, "3 commits pushed, tests failing");

  expect(text.startsWith("> *This was generated by AI during triage.*")).toBe(true);
  expect(text).toContain("tests");
  expect(text).toContain("review.spec");
  expect(text).toContain("fix the two failing unit tests and address the spec review comments");
  expect(text).toContain(branch);
});

test("implement-failed comment carries the AI disclaimer, the worker's reason, and the branch name", () => {
  const text = parkCommentText(implementFailed, branch, "1 commit pushed, incomplete");

  expect(text.startsWith("> *This was generated by AI during triage.*")).toBe(true);
  expect(text).toContain("could not locate the file referenced in the brief");
  expect(text).toContain(branch);
});

test("merge-declined comment carries the AI disclaimer and the branch name", () => {
  const text = parkCommentText(mergeDeclined, branch, "ready to merge, awaiting a different decision");

  expect(text.startsWith("> *This was generated by AI during triage.*")).toBe(true);
  expect(text).toContain(branch);
});

test("every reason's comment also carries the shelved-work state", () => {
  for (const reason of ALL_REASONS) {
    const text = parkCommentText(reason, branch, "shelved-work-marker-xyz");
    expect(text).toContain("shelved-work-marker-xyz");
  }
});

// ───── parkPlan: the exact four-step order, for every reason

test("parkPlan returns the five steps in the specified order", () => {
  expect(parkPlan()).toEqual([
    "push-branch",
    "post-comment",
    "release-claim",
    "swap-label",
    "set-unstarted",
  ]);
});

// ───── remainingPark: every prefix of the four steps

test("remainingPark: nothing done owes every step in order", () => {
  expect(remainingPark(NOTHING_DONE)).toEqual([
    "push-branch",
    "post-comment",
    "release-claim",
    "swap-label",
    "set-unstarted",
  ]);
});

test("remainingPark: branch pushed only owes the remaining four steps", () => {
  const observed: ParkObserved = { ...NOTHING_DONE, branchPushed: true };
  expect(remainingPark(observed)).toEqual(["post-comment", "release-claim", "swap-label", "set-unstarted"]);
});

test("remainingPark: pushed and commented owes the claim release and both tracker writes", () => {
  const observed: ParkObserved = { ...NOTHING_DONE, branchPushed: true, commentPosted: true };
  expect(remainingPark(observed)).toEqual(["release-claim", "swap-label", "set-unstarted"]);
});

test("remainingPark: pushed, commented, and released owes both tracker writes", () => {
  const observed: ParkObserved = {
    ...NOTHING_DONE,
    branchPushed: true,
    commentPosted: true,
    claimReleased: true,
  };
  expect(remainingPark(observed)).toEqual(["swap-label", "set-unstarted"]);
});

// The label swap and the state write are separate tracker writes, and
// PROTOCOL says both matter: a ticket left labelled but still started can
// never re-enter the Queue, so a crash between them must be resumable.
test("remainingPark: a crash between the label swap and the state write owes only the state write", () => {
  const observed: ParkObserved = {
    ...NOTHING_DONE,
    branchPushed: true,
    commentPosted: true,
    claimReleased: true,
    labelSwapped: true,
  };
  expect(remainingPark(observed)).toEqual(["set-unstarted"]);
});

test("remainingPark: every step done owes nothing", () => {
  expect(remainingPark(EVERYTHING_DONE)).toEqual([]);
});

// ───── remainingPark: idempotent on a completed Park

test("remainingPark run twice on a completed Park owes nothing both times", () => {
  expect(remainingPark(EVERYTHING_DONE)).toEqual([]);
  expect(remainingPark(EVERYTHING_DONE)).toEqual([]);
});

// ───── the S19 case: crash after push, before any tracker write

test("S19: pushed but no tracker write yet resumes at post-comment, not at push-branch", () => {
  const observed: ParkObserved = { ...NOTHING_DONE, branchPushed: true };
  const remaining = remainingPark(observed);

  expect(remaining[0]).toBe("post-comment");
  expect(remaining).not.toContain("push-branch");
});

test("S19: the resumed comment step reproduces the original text, never a fresh ask", () => {
  // Recovery replays the same durable comment computed from the original
  // reason — it never re-derives a new question or re-triggers the answer
  // wait. The text is a pure function of (reason, branch, workState), so
  // calling it twice for the same crashed run yields byte-identical output.
  const first = parkCommentText(unanswered, branch, "3 commits pushed, tests unrun");
  const second = parkCommentText(unanswered, branch, "3 commits pushed, tests unrun");

  expect(first).toBe(second);
  expect((first.match(/squash or merge for this one\?/g) ?? []).length).toBe(1);
});

// PROTOCOL step 2 requires the disclaimer to OPEN the comment. A containment
// check would still pass if it drifted below the reason or appeared twice.
test("every reason's comment opens with exactly one disclaimer line", () => {
  for (const reason of ALL_REASONS) {
    const text = parkCommentText(reason, branch, "3 commits pushed");
    expect(text.split("\n")[0]).toBe("> *This was generated by AI during triage.*");
    expect((text.match(/This was generated by AI during triage/g) ?? []).length).toBe(1);
  }
});
